server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
      min: 8
      max: 200
  port: 8092
  servlet:
    context-path: /hospital-api

spring:
  datasource:
    driver-class-name: org.apache.phoenix.queryserver.client.Driver
    url: jdbc:phoenix:thin:url=http://sdly.blockelite.cn:17174;serialization=PROTOBUF
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      test-while-idle: true
      max-active: 8
      min-idle: 4
      validation-query: SELECT 1

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    database: 0
    host: sdly.blockelite.cn

    port: 17170
    password: deech3oo-redis
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  quartz:
    job-store-type: memory

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hospital.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.hospital.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  allow-concurrent-login: true
  is-share: false
  token-style: uuid
  isReadCookie: false


wechat:
  app-id: wx42681ad44a73d7fa
  app-secret: bd32d9831b242190a2517af83ec8f141
  pay:
    v3:
      patient-wx-api:
        app-id: wx42681ad44a73d7fa
        app-v3-secret: 6c6085b7a939450d833d8bb3081d4628
        mch-id: 1526972031
        domain: http://内网穿透的外网IP地址和端口/hospital-wx-api
        cert-path: apiclient_cert.p12

tencent:
  cloud:
    appId: 你的腾讯云APPID
    secretId: 你的腾讯云secretId
    secretKey: 你的腾讯云secretKey
    face:
      groupName: hospital
      region: ap-beijing
  trtc:
    appId: 112233
    secretKey: TRTC的secretKey
    expire: 86400

minio:
  endpoint: http://sdly.blockelite.cn:17168
  access-key: root
  secret-key: deech3oo-minio

